//! `supersonic-harness` — the adversarial proof harness.
//!
//! Runs real classifiers (see `classifiers.rs`) against bundles generated by the
//! real SDK and reports the attacker's measured advantage over the `1/K` baseline,
//! per anonymity-set size. This is the number that backs every privacy claim in the
//! README and `PROOF.md` — an empirical result, not an adjective.
//!
//! Usage:
//!   supersonic-harness [--n N] [--seed S] [--out path.json]
//!
//! Defaults: N=5000 bundles per train/test split, seed=1, K ∈ {2,4,8,16}.

mod classifiers;
mod eval;
mod learned;

use eval::{eval_k, KResult};
use serde::Serialize;
use supersonic_sdk::DecoyConfig;

#[derive(Serialize)]
struct Report {
    n_per_split: usize,
    seed: u64,
    sigma: f64,
    round_match_prob: f64,
    results: Vec<KResult>,
}

fn main() {
    let mut n = 5000usize;
    let mut seed = 1u64;
    let mut out: Option<String> = None;
    let mut cfg = DecoyConfig::default();

    let args: Vec<String> = std::env::args().collect();
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--n" => {
                i += 1;
                n = args[i].parse().expect("--n <usize>");
            }
            "--seed" => {
                i += 1;
                seed = args[i].parse().expect("--seed <u64>");
            }
            "--sigma" => {
                i += 1;
                cfg.sigma = args[i].parse().expect("--sigma <f64>");
            }
            "--round-match" => {
                i += 1;
                cfg.round_match_prob = args[i].parse().expect("--round-match <f64>");
            }
            "--out" => {
                i += 1;
                out = Some(args[i].clone());
            }
            other => {
                eprintln!("unknown arg: {other}");
                std::process::exit(2);
            }
        }
        i += 1;
    }

    let ks = [2usize, 4, 8, 16];
    let results: Vec<KResult> = ks.iter().map(|&k| eval_k(k, n, cfg, seed)).collect();

    print_table(&results, n);

    let report = Report {
        n_per_split: n,
        seed,
        sigma: cfg.sigma,
        round_match_prob: cfg.round_match_prob,
        results,
    };

    if let Some(path) = out {
        let json = serde_json::to_string_pretty(&report).unwrap();
        std::fs::write(&path, json).expect("write report json");
        println!("\nwrote machine-readable report to {path}");
    }
}

fn print_table(results: &[KResult], n: usize) {
    println!("supersonic-tx — adversarial proof harness");
    println!("{n} bundles per train/test split · real amounts sampled log-uniform 0.001-100 SOL\n");
    println!("  K  | baseline | best attack          | adv (test) | interpretation      | consolidation adv");
    println!("-----+----------+----------------------+------------+---------------------+------------------");
    for r in results {
        let interp = interpret(r.adversary_test_advantage, r.baseline);
        println!(
            "  {:>2} | {:>7.3} | {:<20} | {:>+9.4} | {:<19} | {:>+9.4}",
            r.k,
            r.baseline,
            r.best_classifier,
            r.adversary_test_advantage,
            interp,
            r.naive_consolidation_advantage,
        );
    }
    println!();
    println!("adv (test) = (attacker accuracy on held-out bundles) - 1/K.");
    println!("~0 => the attacker does no better than a random guess (the goal).");
    println!("consolidation adv = worst case if decoys are swept back immediately (THREAT_MODEL §4.6);");
    println!("mitigated by delaying/dispersing recovery or keeping decoys live (account-cooker).");
}

fn interpret(adv: f64, baseline: f64) -> &'static str {
    let ratio = adv / baseline;
    if adv <= 0.02 || ratio <= 0.10 {
        "indistinguishable"
    } else if ratio <= 0.30 {
        "weak leak"
    } else {
        "LEAKS - fix generator"
    }
}
