//! `supersonic-harness` — the adversarial proof harness.
//!
//! Runs real classifiers (see `classifiers.rs`) against bundles generated by the
//! real SDK and reports the attacker's measured advantage over the `1/K` baseline,
//! per anonymity-set size. This is the number that backs every privacy claim in the
//! README and `PROOF.md` — an empirical result, not an adjective.
//!
//! Usage:
//!   supersonic-harness [--n N] [--seed S] [--out path.json]
//!
//! Defaults: N=5000 bundles per train/test split, seed=1, K ∈ {2,4,8,16}.

mod classifiers;
mod consolidation;
mod destination;
mod eval;
mod forest;
mod history_fixture;
mod learned;
mod mainnet_channel;
mod mainnet_fixture;

use eval::{eval_k, KResult};
use serde::Serialize;
use supersonic_sdk::DecoyConfig;

#[derive(Serialize)]
struct Report {
    n_per_split: usize,
    seed: u64,
    sigma: f64,
    round_match_prob: f64,
    results: Vec<KResult>,
}

fn main() {
    let mut n = 5000usize;
    let mut seed = 1u64;
    let mut out: Option<String> = None;
    let mut cfg = DecoyConfig::default();

    let args: Vec<String> = std::env::args().collect();
    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--n" => {
                i += 1;
                n = args[i].parse().expect("--n <usize>");
            }
            "--seed" => {
                i += 1;
                seed = args[i].parse().expect("--seed <u64>");
            }
            "--sigma" => {
                i += 1;
                cfg.sigma = args[i].parse().expect("--sigma <f64>");
            }
            "--round-match" => {
                i += 1;
                cfg.round_match_prob = args[i].parse().expect("--round-match <f64>");
            }
            "--out" => {
                i += 1;
                out = Some(args[i].clone());
            }
            other => {
                eprintln!("unknown arg: {other}");
                std::process::exit(2);
            }
        }
        i += 1;
    }

    let ks = [2usize, 4, 8, 16];
    let results: Vec<KResult> = ks.iter().map(|&k| eval_k(k, n, cfg, seed)).collect();

    print_table(&results, n);
    print_fixture_provenance();
    print_mainnet_fixture_provenance();

    let report = Report {
        n_per_split: n,
        seed,
        sigma: cfg.sigma,
        round_match_prob: cfg.round_match_prob,
        results,
    };

    if let Some(path) = out {
        let json = serde_json::to_string_pretty(&report).unwrap();
        std::fs::write(&path, json).expect("write report json");
        println!("\nwrote machine-readable report to {path}");
    }
}

fn print_table(results: &[KResult], n: usize) {
    println!("supersonic-tx — adversarial proof harness");
    println!("{n} bundles per train/test split · real amounts sampled log-uniform 0.001-100 SOL\n");
    println!("  K  | baseline | best attack          | adv (test) | interpretation      | consolidation: naive -> disperse");
    println!("-----+----------+----------------------+------------+---------------------+---------------------------------");
    for r in results {
        let interp = interpret(r.adversary_test_advantage, r.baseline);
        println!(
            "  {:>2} | {:>7.3} | {:<20} | {:>+9.4} | {:<19} | {:>+8.4} -> {:>+8.4}",
            r.k,
            r.baseline,
            r.best_classifier,
            r.adversary_test_advantage,
            interp,
            r.naive_consolidation_advantage,
            r.dispersed_consolidation_advantage,
        );
    }
    println!();
    println!("  K  | destination-history (MODELED): naive -> warm  | destination-history (MEASURED, real devnet): naive -> warm");
    println!("-----+-------------------------------------------------+-------------------------------------------------------------");
    for r in results {
        println!(
            "  {:>2} | {:>+8.4} -> {:>+8.4}                       | {:>+8.4} -> {:>+8.4}",
            r.k,
            r.naive_history_advantage,
            r.prewarmed_history_advantage,
            r.naive_history_measured_advantage,
            r.prewarmed_history_measured_advantage,
        );
    }
    println!();
    println!("adv (test) = (attacker accuracy on held-out bundles) - 1/K.");
    println!("~0 => the attacker does no better than a random guess (the goal).");
    println!(
        "best attack now includes a nonlinear extra-trees ensemble (forest.rs) alongside logreg."
    );
    println!("consolidation = measured recovery-linkage advantage (consolidation.rs), naive sweep");
    println!("vs `recover --disperse`: dispersing each decoy to its own sink removes the linkage.");
    println!(
        "destination-history MODELED (destination.rs) = synthetic log-normal, regression reference."
    );
    println!(
        "destination-history MEASURED = bootstrap-resampled from a real devnet fixture (harness/fixtures/devnet_history.json)."
    );
    println!("Both regimes: a companion account-cooker that pre-warms decoy destinations closes the channel (number, not promise).");
    println!();
    println!("  K  | mainnet destination-history: naive -> warm | mainnet funding-graph: naive -> warm | mainnet token-holdings: naive -> warm");
    println!("-----+---------------------------------------------+----------------------------------------+----------------------------------------");
    for r in results {
        println!(
            "  {:>2} | {:>+8.4} -> {:>+8.4}                 | {:>+8.4} -> {:>+8.4}                    | {:>+8.4} -> {:>+8.4}",
            r.k,
            r.naive_mainnet_history_advantage,
            r.prewarmed_mainnet_history_advantage,
            r.naive_mainnet_funding_advantage,
            r.prewarmed_mainnet_funding_advantage,
            r.naive_mainnet_tokens_advantage,
            r.prewarmed_mainnet_tokens_advantage,
        );
    }
    println!();
    println!("mainnet channels above are MEASURED against real, passively-observed mainnet-beta");
    println!(
        "addresses (harness/fixtures/mainnet_profiles.json), evaluated only on that fixture's"
    );
    println!();
    println!("  K  | funding-graph (idealized ceiling, warm) | funding-graph (SHIPPED, same-wallet funder) | funding-graph (SHIPPED, per-slot sub-funder)");
    println!("-----+-------------------------------------------+-----------------------------------------------+------------------------------------------------");
    for r in results {
        println!(
            "  {:>2} | {:>+8.4}                                | {:>+8.4}                                       | {:>+8.4}",
            r.k,
            r.prewarmed_mainnet_funding_advantage,
            r.mainnet_funding_shipped_advantage,
            r.mainnet_funding_shipped_subfunder_pool_advantage,
        );
    }
    println!();
    println!(
        "SHIPPED mechanism residual = predict_by_shared_funder (mainnet_channel.rs): decoys all"
    );
    println!(
        "carry the literal warm_pool funder wallet, the real leg carries a real held-out payee's"
    );
    println!(
        "real earliest_funder_proxy; the attacker just picks whichever of the K funders differs"
    );
    println!(
        "from the rest. This is the honest residual of what `--decoy-mode warm-pool` ships today,"
    );
    println!("not an idealized ceiling. See THREAT_MODEL.md §4.7 and PROOF.md §3f.");
    println!();
    println!(
        "per-slot sub-funder residual = same attacker, after `warm_pool` funds each pool slot from"
    );
    println!(
        "its own dedicated wallet (`sdk/src/warming.rs::derive_subfunder_keypair`) instead of one"
    );
    println!(
        "shared wallet — no majority funder left to compare against, so this same-hop attacker's"
    );
    println!(
        "advantage measures to exactly 0.0. Does NOT model a stronger attacker who traces one hop"
    );
    println!("further (each sub-funder's own funder is still `payer`) — see THREAT_MODEL.md §6.");
    println!();
    println!(
        "IMPORTANT — what `--decoy-mode warm-pool` (`supersonic warm`) actually closes vs. what"
    );
    println!(
        "these numbers show: destination-history and token-holdings are closed by the SHIPPED"
    );
    println!(
        "mechanism (warm_pool creates real signature history AND a real token account per slot)."
    );
    println!(
        "Funding-graph's `warm` number above is an IDEALIZED ceiling — it resamples real aged"
    );
    println!(
        "addresses' actual funder diversity, which `warm_pool` does NOT reproduce: every pool slot"
    );
    println!(
        "is funded by the same wallet. This channel is NOT closed by the shipped mechanism; treat"
    );
    println!(
        "the funding-graph `warm` column as an aspirational target, not a claim. See THREAT_MODEL.md."
    );
    println!(
        "`held_out` split — `calibration` is reserved for whatever mechanism (e.g. an SDK-side"
    );
    println!("warming pool) fits something to the data, kept disjoint from what measures it.");
}

/// Print where the MEASURED destination-history numbers actually came from, so the
/// claim is checkable, not just a label — the fixture's own `collected_at`/`cluster`,
/// sample sizes, and the first few pubkeys (full list + counts in the fixture file).
fn print_fixture_provenance() {
    let f = history_fixture::HistoryFixture::load();
    println!(
        "MEASURED fixture provenance: {} addresses (cluster={}, collected_at={}), {} aged + {} fresh_verified_zero.",
        f.aged.len() + f.fresh_verified_zero.len(),
        f.cluster,
        f.collected_at,
        f.aged.len(),
        f.fresh_verified_zero.len(),
    );
    println!("methodology: {}", f.methodology);
    if let Some(sample) = f.aged.first() {
        println!(
            "  e.g. aged: {} -> {} real signatures (verify: solana transaction-history <ADDRESS> / explorer, cluster={})",
            sample.pubkey, sample.signature_count, f.cluster
        );
    }
    if let Some(sample) = f.fresh_verified_zero.first() {
        println!(
            "  e.g. fresh: {} -> {} real signatures (independently re-verifiable)",
            sample.pubkey, sample.signature_count
        );
    }
    println!("  full list: harness/fixtures/devnet_history.json");
}

/// Same purpose as `print_fixture_provenance`, for the mainnet fixture: make the
/// MEASURED mainnet-channel numbers checkable, not just labeled.
fn print_mainnet_fixture_provenance() {
    let f = mainnet_fixture::MainnetFixture::load();
    let held_out_aged = f.aged_held_out().len();
    let held_out_fresh = f.fresh_held_out().len();
    println!(
        "\nMAINNET fixture provenance: {} addresses total (cluster={}, collected_at={}), {} aged \
         + {} fresh_verified_zero ({} aged + {} fresh in the held_out split actually evaluated \
         above; the rest is `calibration`, reserved).",
        f.aged.len() + f.fresh_verified_zero.len(),
        f.cluster,
        f.collected_at,
        f.aged.len(),
        f.fresh_verified_zero.len(),
        held_out_aged,
        held_out_fresh,
    );
    println!("methodology: {}", f.methodology);
    if let Some(sample) = f.aged.first() {
        println!(
            "  e.g. aged: {} -> {} sigs (lower bound if capped), funder={:?}, {} token accounts, split={} (verify: solana transaction-history <ADDRESS>, cluster={})",
            sample.pubkey, sample.signature_count_lower_bound, sample.earliest_funder_proxy, sample.token_account_count, sample.split, f.cluster
        );
    }
    if let Some(sample) = f.fresh_verified_zero.first() {
        println!(
            "  e.g. fresh: {} -> {} sigs, {} token accounts (independently re-verifiable)",
            sample.pubkey, sample.signature_count_lower_bound, sample.token_account_count
        );
    }
    println!("  full list: harness/fixtures/mainnet_profiles.json");
}

fn interpret(adv: f64, baseline: f64) -> &'static str {
    let ratio = adv / baseline;
    if adv <= 0.02 || ratio <= 0.10 {
        "indistinguishable"
    } else if ratio <= 0.30 {
        "weak leak"
    } else {
        "LEAKS - fix generator"
    }
}
