//! Per-slot round-trip targets for `supersonic warm`, derived from real
//! mainnet calibration data instead of applying the same `--rounds` value to
//! every pool slot.
//!
//! **Why this exists.** Before this module, `warm_pool()` in `main.rs` ran
//! exactly `rounds` fund-in/sweep-back round trips on every slot, so every
//! warmed slot ended with an identical `rounds * 2` signature count — a
//! perfectly uniform, suspiciously round number repeated across the whole
//! pool. Real mainnet addresses don't look like that; they have real
//! dispersion in signature counts. Uniformity-as-a-tell is exactly what an
//! attacker comparing several decoys from the same pool would notice, no
//! matter how "real" each individual round trip is. This module breaks that
//! uniformity by deriving a per-slot round-trip target from an actual
//! distribution of real mainnet signature counts, deterministically seeded
//! per slot.
//!
//! **What this does not claim.** It does not replicate the *magnitude* of
//! real mainnet history (see `target_rounds_for_slot` doc below for why that
//! specific number is unreachable for a self-funded CLI run) — only the
//! *relative dispersion* around the round-trip budget (`--rounds`) the user
//! already chose. See `sdk/src/warming.rs`'s module doc for the fuller
//! picture of what warm-pool does and does not close.

use rand::Rng;
use rand::SeedableRng;
use rand_chacha::ChaCha20Rng;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use zeroize::Zeroize;

/// Same frozen fixture the harness measures against
/// (`harness/src/mainnet_fixture.rs`), reused here directly rather than
/// depending on the `harness` crate (which has no `[lib]` target, only bins).
/// `cli/` and `harness/` are sibling directories under the repo root, so this
/// path is `cli/src/` -> `../../` (repo root) -> `harness/fixtures/...`.
const RAW_FIXTURE: &str = include_str!("../../harness/fixtures/mainnet_profiles.json");

const KDF_WARM_PROFILE: &[u8] = b"supersonic-tx/warm-profile/v1";

#[derive(Deserialize)]
struct RawProfile {
    signature_count_lower_bound: u64,
    signature_count_exact: bool,
    split: String,
}

#[derive(Deserialize)]
struct RawFixture {
    aged: Vec<RawProfile>,
}

/// Fallback calibration pool, used only if the parsed fixture's usable
/// calibration subset comes back empty (defensive: shouldn't happen with the
/// fixture committed today, but the fixture can be regenerated by
/// `collect-mainnet-profiles` in the future and this must never panic or
/// error if that regeneration ever produces an unusable calibration split).
/// These nine values are drawn straight from today's real calibration set's
/// `signature_count_exact == true` subset, spanning its low/median/high
/// range (min 1, up through the median ~92, up to near-max 997) — not
/// synthesized shapes, just a small frozen slice of the real numbers as a
/// last resort.
const FALLBACK_POOL: &[u64] = &[1, 2, 4, 20, 92, 211, 409, 655, 997];

/// Real calibration-split, exact-count signature counts usable as a warm
/// target distribution.
///
/// Only `split == "calibration" && signature_count_exact == true` entries are
/// used. The other 349/535 calibration entries have `signature_count_exact ==
/// false` — they hit the collector's pagination cap (1000 signatures) and
/// are lower bounds, not a real, replicable, payable target: a self-funded
/// CLI run cannot round-trip an address to "at least 1000, unknown how much
/// more" in any principled way. The 186 exact entries are real, confirmed,
/// finite counts, so they're what this module fits a target distribution to.
/// `held_out` entries are never touched here — `harness/src/mainnet_fixture.rs`
/// reserves that split for measurement only.
fn calibration_pool() -> Vec<u64> {
    let parsed: Option<RawFixture> = serde_json::from_str(RAW_FIXTURE).ok();
    let pool: Vec<u64> = parsed
        .map(|f| {
            f.aged
                .into_iter()
                .filter(|p| p.split == "calibration" && p.signature_count_exact)
                .map(|p| p.signature_count_lower_bound)
                .collect()
        })
        .unwrap_or_default();
    if pool.is_empty() {
        FALLBACK_POOL.to_vec()
    } else {
        pool
    }
}

fn median(values: &[u64]) -> f64 {
    let mut v = values.to_vec();
    v.sort_unstable();
    let n = v.len();
    if n % 2 == 1 {
        v[n / 2] as f64
    } else {
        (v[n / 2 - 1] as f64 + v[n / 2] as f64) / 2.0
    }
}

/// Compute how many fund-in/sweep-back round trips `slot` should get this
/// run, given the user's `base_rounds` (the `--rounds` CLI value).
///
/// Deterministic in `(master_seed, slot, base_rounds)` — same derivation
/// pattern as `sdk/src/warming.rs` (`Sha256(tag || master_seed ||
/// slot.to_le_bytes())` seeding a `ChaCha20Rng`), but a distinct domain tag
/// so it never collides with pool-member-keypair or pool-selection
/// derivation.
///
/// Picks a real value from the calibration pool, scales it against the
/// pool's own median to get a relative jitter factor in `[0.25, 3.0]`, then
/// applies that factor to `base_rounds`. This reproduces the *shape* of real
/// dispersion (some slots end up with meaningfully more or fewer round trips
/// than others) without attempting to reach real mainnet *magnitude* --
/// 349/535 (65%) of this same calibration split hit the collector's 1000-
/// signature pagination cap, i.e. real addresses commonly have signature
/// counts that are not a reachable, payable target for a self-funded CLI run
/// doing real round trips. What's reproduced here is dispersion around the
/// budget the user already chose via `--rounds`/`--pool-size`, not the
/// absolute scale of mainnet history.
pub fn target_rounds_for_slot(master_seed: &[u8; 32], slot: u32, base_rounds: u32) -> u32 {
    let pool = calibration_pool();
    let med = median(&pool);

    let mut h = Sha256::new();
    h.update(KDF_WARM_PROFILE);
    h.update(master_seed);
    h.update(slot.to_le_bytes());
    // Intermediate 32-byte RNG seed derived from `master_seed` — an owned local
    // buffer, wiped explicitly once consumed by `ChaCha20Rng::from_seed` rather
    // than left lingering in memory (same pattern as `sdk/src/lib.rs::bundle_rng`
    // and `sdk/src/warming.rs`).
    let mut seed: [u8; 32] = h.finalize().into();
    let mut rng = ChaCha20Rng::from_seed(seed);
    seed.zeroize();

    let raw = pool[rng.gen_range(0..pool.len())];
    let jitter = (raw as f64 / med).clamp(0.25, 3.0);
    let target = ((base_rounds as f64) * jitter).round().max(1.0);
    target as u32
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    const SEED: [u8; 32] = [17u8; 32];

    #[test]
    fn deterministic_for_same_inputs() {
        let a = target_rounds_for_slot(&SEED, 5, 3);
        let b = target_rounds_for_slot(&SEED, 5, 3);
        assert_eq!(a, b, "same master_seed/slot/base_rounds must always agree");
    }

    #[test]
    fn varies_across_slots_not_uniform() {
        let base_rounds = 4;
        let values: Vec<u32> = (0..64)
            .map(|slot| target_rounds_for_slot(&SEED, slot, base_rounds))
            .collect();
        let distinct: HashSet<u32> = values.iter().copied().collect();
        assert!(
            distinct.len() >= 5,
            "expected real dispersion across 64 slots, got only {} distinct values: {:?}",
            distinct.len(),
            values
        );
    }

    #[test]
    fn stays_within_clamp_bounds() {
        let base_rounds = 10u32;
        let lo = ((base_rounds as f64) * 0.25).floor().max(1.0) as u32;
        let hi = ((base_rounds as f64) * 3.0).ceil() as u32;
        for slot in 0..64u32 {
            let target = target_rounds_for_slot(&SEED, slot, base_rounds);
            assert!(
                target >= lo.saturating_sub(1) && target <= hi + 1,
                "slot {slot} target {target} out of expected bound [{lo}, {hi}] (base_rounds={base_rounds})"
            );
            assert!(target >= 1, "target rounds must never be 0");
        }
    }
}
